// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/whitelist.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthTokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthTokenResponse) Reset() {
	*x = AuthTokenResponse{}
	mi := &file_proto_whitelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenResponse) ProtoMessage() {}

func (x *AuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whitelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenResponse.ProtoReflect.Descriptor instead.
func (*AuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_whitelist_proto_rawDescGZIP(), []int{0}
}

func (x *AuthTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthTokenResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseKey    string                 `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Hwid          string                 `protobuf:"bytes,3,opt,name=hwid,proto3" json:"hwid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_proto_whitelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whitelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_whitelist_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *ValidateRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ValidateRequest) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_proto_whitelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whitelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_whitelist_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseKey    string                 `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLicenseRequest) Reset() {
	*x = UpdateLicenseRequest{}
	mi := &file_proto_whitelist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLicenseRequest) ProtoMessage() {}

func (x *UpdateLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whitelist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLicenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateLicenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_whitelist_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLicenseRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *UpdateLicenseRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateLicenseRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseKey    string                 `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLicenseRequest) Reset() {
	*x = DeleteLicenseRequest{}
	mi := &file_proto_whitelist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLicenseRequest) ProtoMessage() {}

func (x *DeleteLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whitelist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLicenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteLicenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_whitelist_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteLicenseRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

var File_proto_whitelist_proto protoreflect.FileDescriptor

const file_proto_whitelist_proto_rawDesc = "" +
	"\n" +
	"\x15proto/whitelist.proto\x12\twhitelist\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"W\n" +
	"\x11AuthTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x03R\x10expiresInSeconds\"e\n" +
	"\x0fValidateRequest\x12\x1f\n" +
	"\vlicense_key\x18\x01 \x01(\tR\n" +
	"licenseKey\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04hwid\x18\x03 \x01(\tR\x04hwid\"B\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"s\n" +
	"\x14UpdateLicenseRequest\x12\x1f\n" +
	"\vlicense_key\x18\x01 \x01(\tR\n" +
	"licenseKey\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"7\n" +
	"\x14DeleteLicenseRequest\x12\x1f\n" +
	"\vlicense_key\x18\x01 \x01(\tR\n" +
	"licenseKey2\xaf\x03\n" +
	"\x10WhitelistService\x12_\n" +
	"\fGetAuthToken\x12\x16.google.protobuf.Empty\x1a\x1c.whitelist.AuthTokenResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/token\x12k\n" +
	"\x0fValidateLicense\x12\x1a.whitelist.ValidateRequest\x1a\x1b.whitelist.ValidateResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/license/validate\x12`\n" +
	"\rUpdateLicense\x12\x1f.whitelist.UpdateLicenseRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/v1/license\x12k\n" +
	"\rDeleteLicense\x12\x1f.whitelist.DeleteLicenseRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/license/{license_key}B-Z+github.com/mkseven15/whitelist-server/protob\x06proto3"

var (
	file_proto_whitelist_proto_rawDescOnce sync.Once
	file_proto_whitelist_proto_rawDescData []byte
)

func file_proto_whitelist_proto_rawDescGZIP() []byte {
	file_proto_whitelist_proto_rawDescOnce.Do(func() {
		file_proto_whitelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_whitelist_proto_rawDesc), len(file_proto_whitelist_proto_rawDesc)))
	})
	return file_proto_whitelist_proto_rawDescData
}

var file_proto_whitelist_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_whitelist_proto_goTypes = []any{
	(*AuthTokenResponse)(nil),    // 0: whitelist.AuthTokenResponse
	(*ValidateRequest)(nil),      // 1: whitelist.ValidateRequest
	(*ValidateResponse)(nil),     // 2: whitelist.ValidateResponse
	(*UpdateLicenseRequest)(nil), // 3: whitelist.UpdateLicenseRequest
	(*DeleteLicenseRequest)(nil), // 4: whitelist.DeleteLicenseRequest
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_proto_whitelist_proto_depIdxs = []int32{
	5, // 0: whitelist.WhitelistService.GetAuthToken:input_type -> google.protobuf.Empty
	1, // 1: whitelist.WhitelistService.ValidateLicense:input_type -> whitelist.ValidateRequest
	3, // 2: whitelist.WhitelistService.UpdateLicense:input_type -> whitelist.UpdateLicenseRequest
	4, // 3: whitelist.WhitelistService.DeleteLicense:input_type -> whitelist.DeleteLicenseRequest
	0, // 4: whitelist.WhitelistService.GetAuthToken:output_type -> whitelist.AuthTokenResponse
	2, // 5: whitelist.WhitelistService.ValidateLicense:output_type -> whitelist.ValidateResponse
	5, // 6: whitelist.WhitelistService.UpdateLicense:output_type -> google.protobuf.Empty
	5, // 7: whitelist.WhitelistService.DeleteLicense:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_whitelist_proto_init() }
func file_proto_whitelist_proto_init() {
	if File_proto_whitelist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_whitelist_proto_rawDesc), len(file_proto_whitelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_whitelist_proto_goTypes,
		DependencyIndexes: file_proto_whitelist_proto_depIdxs,
		MessageInfos:      file_proto_whitelist_proto_msgTypes,
	}.Build()
	File_proto_whitelist_proto = out.File
	file_proto_whitelist_proto_goTypes = nil
	file_proto_whitelist_proto_depIdxs = nil
}
