// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/whitelist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhitelistService_GetAuthToken_FullMethodName    = "/whitelist.WhitelistService/GetAuthToken"
	WhitelistService_ValidateLicense_FullMethodName = "/whitelist.WhitelistService/ValidateLicense"
	WhitelistService_UpdateLicense_FullMethodName   = "/whitelist.WhitelistService/UpdateLicense"
	WhitelistService_DeleteLicense_FullMethodName   = "/whitelist.WhitelistService/DeleteLicense"
)

// WhitelistServiceClient is the client API for WhitelistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Whitelist Service Definition
type WhitelistServiceClient interface {
	// 1. Get a One-Time Access Token (Public)
	GetAuthToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthTokenResponse, error)
	// 2. Validate a License Key (Requires OTAT)
	ValidateLicense(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// 3. Create/Update License (Admin Only)
	UpdateLicense(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 4. Delete License (Admin Only)
	DeleteLicense(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type whitelistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhitelistServiceClient(cc grpc.ClientConnInterface) WhitelistServiceClient {
	return &whitelistServiceClient{cc}
}

func (c *whitelistServiceClient) GetAuthToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, WhitelistService_GetAuthToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) ValidateLicense(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, WhitelistService_ValidateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) UpdateLicense(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WhitelistService_UpdateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whitelistServiceClient) DeleteLicense(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WhitelistService_DeleteLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhitelistServiceServer is the server API for WhitelistService service.
// All implementations must embed UnimplementedWhitelistServiceServer
// for forward compatibility.
//
// The Whitelist Service Definition
type WhitelistServiceServer interface {
	// 1. Get a One-Time Access Token (Public)
	GetAuthToken(context.Context, *emptypb.Empty) (*AuthTokenResponse, error)
	// 2. Validate a License Key (Requires OTAT)
	ValidateLicense(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// 3. Create/Update License (Admin Only)
	UpdateLicense(context.Context, *UpdateLicenseRequest) (*emptypb.Empty, error)
	// 4. Delete License (Admin Only)
	DeleteLicense(context.Context, *DeleteLicenseRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWhitelistServiceServer()
}

// UnimplementedWhitelistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhitelistServiceServer struct{}

func (UnimplementedWhitelistServiceServer) GetAuthToken(context.Context, *emptypb.Empty) (*AuthTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthToken not implemented")
}
func (UnimplementedWhitelistServiceServer) ValidateLicense(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateLicense not implemented")
}
func (UnimplementedWhitelistServiceServer) UpdateLicense(context.Context, *UpdateLicenseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLicense not implemented")
}
func (UnimplementedWhitelistServiceServer) DeleteLicense(context.Context, *DeleteLicenseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLicense not implemented")
}
func (UnimplementedWhitelistServiceServer) mustEmbedUnimplementedWhitelistServiceServer() {}
func (UnimplementedWhitelistServiceServer) testEmbeddedByValue()                          {}

// UnsafeWhitelistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhitelistServiceServer will
// result in compilation errors.
type UnsafeWhitelistServiceServer interface {
	mustEmbedUnimplementedWhitelistServiceServer()
}

func RegisterWhitelistServiceServer(s grpc.ServiceRegistrar, srv WhitelistServiceServer) {
	// If the following call panics, it indicates UnimplementedWhitelistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhitelistService_ServiceDesc, srv)
}

func _WhitelistService_GetAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).GetAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_GetAuthToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).GetAuthToken(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_ValidateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).ValidateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_ValidateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).ValidateLicense(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_UpdateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).UpdateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_UpdateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).UpdateLicense(ctx, req.(*UpdateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhitelistService_DeleteLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistServiceServer).DeleteLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistService_DeleteLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistServiceServer).DeleteLicense(ctx, req.(*DeleteLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhitelistService_ServiceDesc is the grpc.ServiceDesc for WhitelistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhitelistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whitelist.WhitelistService",
	HandlerType: (*WhitelistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthToken",
			Handler:    _WhitelistService_GetAuthToken_Handler,
		},
		{
			MethodName: "ValidateLicense",
			Handler:    _WhitelistService_ValidateLicense_Handler,
		},
		{
			MethodName: "UpdateLicense",
			Handler:    _WhitelistService_UpdateLicense_Handler,
		},
		{
			MethodName: "DeleteLicense",
			Handler:    _WhitelistService_DeleteLicense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/whitelist.proto",
}
